<template>
  <div class="disease">
    <tree-info :treeData="treeData" :treeItemData="treeItemData"></tree-info>
    <table-info :breadcrumbList="breadcrumbList" :tableData="tableData"></table-info>
  </div>
</template>

<script>
import TableInfo from './components/DiseaseTable'
import TreeInfo from './components/DiseaseTree'
export default {
  name: 'disease',
  components: { TableInfo, TreeInfo },
  data () {
    return {
      breadcrumbList: ['疾病', '外科'],
      tableData: [
        {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }, {
          type: '疾病',
          sort: '内科',
          num: 'LY01082794',
          order: '16',
          name: '注射用头孢肟',
          spec: '1g（头孢噻肟）',
          base: '头孢，头孢',
          anti: '抗菌药物',
          vender: '东北制药集团'
        }
      ],
      treeData: [
        {
          name: 'jb',
          title: '疾病',
          icon: ''
        }, {
          name: 'ss',
          title: '手术',
          icon: ''
        }, {
          name: 'zl',
          title: '肿瘤形态学',
          icon: ''
        }, {
          name: 'zyjb',
          title: '中医疾病',
          icon: ''
        }, {
          name: 'zyzh',
          title: '中医症候',
          icon: ''
        }
      ],
      treeItemData: ['内科', '外科', '皮肤科', '心内科', '血液科', '肿瘤科', '儿童科', '康复科', '妇产科', '中医科', '感染科', '呼吸科']
    }
  },
  methods: {
    setBreadcrumbList (list) {
      this.breadcrumbList = list
    }
  }
}
</script>

<style scoped lang="scss">
.disease {
  display: flex;
  width: 100%;
  height: 100%;
  // background-color: #f0f3f8;
}
</style>